gcloud functions deploy gmail-agent-processor \
  --gen2 \
  --runtime python312 \
  --region us-central1 \
  --source . \
  --entry-point process_new_email \
  --trigger-topic gmail_bot_messages \
  --env-vars-file env.yaml \
  --timeout 540s \
  --service-account gmail-bot-sa@vraie-3a692.iam.gserviceaccount.com \
  --memory 512MiB \
